### ISSUE TITLE
[Feature Request] Add Chezh Krona

### ISSUE THREAD

**Issue by Andrewsudarikov** [matfantinel/moneta#19]
Chezh Republic is a very popular tourist destination, so its currency would be a welcome addition to the app. 

Please note that in Chezh Republic, even though it is a member of the Euro zone, its own national currency is a preferred payment medium, so this is very important for any tourist going there.

**Comment by matfantinel** [comment]
Thanks for the request!

I just checked and that currency is available on the API I use. It's ISO symbol is `CZK` for reference.

I can add it when I got the time or someone else can open a PR if possible :)

**Comment by matfantinel** [comment]
Closed by #24
