### ISSUE TITLE
3 needs : TWD (Taiwan Dollar required) + Exchange value when minimized + Update every settings

### ISSUE THREAD

**Issue by ghost** [matfantinel/moneta#32]
Hi,

I finally found your Moneta program I was looking since month as a perfect tool for me.
Sincerely thank you for your work about it.

I just have 3 request to upgrade it :
1) I personally need the TWD (Taiwan Dollar exchange) to EUR for all my family. Thank you.

2) To keep Moneta efficient it should be better when it has been minimized (on linux) to display on its title (minimized form) the chosen values in place of "com.github.matfantinel..." (I got after having installed it on Debian with flatpak. By example it should be better to see "$1,0831 / 1€" in place of "com.github.matfantinel...". It gives to Moneta a better way to always keep it visible without keeping it above other opened windows

3)  Having a combo box to select the periodicity of currency exchange should be appreciate in place of fixing it to 10 minutes. The values from 5 to 60 minutes by order of 5 or 10 or 15 or 30 or 45 or 60 must be better.

Sincerely thank you for considering all those 3 needs.

With pleasure to continue using Moneta as a reference I will soon recommand to others ;-)

Have a nice day.

Miguipda

**Comment by matfantinel** [comment]
Hey!

1 - I believe TWD can be added, should be easy to do. I just need some time to work on the next release;
2 - I had never really thought of that as I develop on elementary and there are no window titles :stuck_out_tongue_closed_eyes: . Should be somewhat easy to do for the next release also;
3 - Personally I wouldn't like to fiddle much with that. I'm using the only trustworth free API for currencies that I could find, but I wouldn't like to abuse it much - there's no clear limit of how many requests can be made for an IP, but they still ask to prevent abuse. I've had my IP blocked for a few minutes while developing it with a lower time interval. So I think that at least for now keeping it as 10min is a safe spot

**Comment by ghost** [comment]
Sincerely thank you

Le February 16, 2020 5:49:35 PM UTC, Matheus Fantinel <notifications@github.com> a écrit :
>Hey!
>
>1 - I believe TWD can be added, should be easy to do. I just need some
>time to work on the next release;
>2 - I had never really thought of that as I develop on elementary and
>there are no window titles :stuck_out_tongue_closed_eyes: . Should be
>somewhat easy to do for the next release also;
>3 - Personally I wouldn't like to fiddle much with that. I'm using the
>only trustworth free API for currencies that I could find, but I
>wouldn't like to abuse it much - there's no clear limit of how many
>requests can be made for an IP, but they still ask to prevent abuse.
>I've had my IP blocked for a few minutes while developing it with a
>lower time interval. So I think that at least for now keeping it as
>10min is a safe spot
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matfantinel/moneta/issues/32#issuecomment-586733458

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
