### ISSUE TITLE
Solve the freeze that happens while waiting for the API response

### ISSUE THREAD

**Issue by matfantinel** [matfantinel/moneta#38]
When changing currencies, the app freezes for a bit while waiting for the API to respond. We should get rid of this to make the app feel snappier.

**Comment by rajkumaar23** [comment]
And, what's your idea on fixing that ? A progress message that says `Please wait`  ?

**Comment by matfantinel** [comment]
@rajkumaar23 not necessarily, although that would be nice.

Main problem is that the entire UI freezes while waiting for the API response. I think it has to be fired asynchronously, so that UI is still usable while it's loading data.

So instead of one job, like this:

Change currency(UI freezes) -> ask API what's the value -> wait for response -> write value in screen -> Done (UI unfreezes)

We'd have two separate processes:

Change currency -> Fires the refresh process -> Done
Ask API what's the value -> wait for response -> write value in screen -> Done

This way the UI doesn't freeze

**Comment by rajkumaar23** [comment]
Cool, will try that out.
