### ISSUE TITLE
Display rates from the past

### ISSUE THREAD

**Issue by dkerkow** [matfantinel/moneta#49]
When doing my accounting, I often need to know what the exchange rate was in the past, at a specific point in time (daily resolution).

Would that be possible with the API you are using? If yes, it would be a very handy extra feature. Thank you for considering.

**Comment by matfantinel** [comment]
Hi @dkerkow !

Unfortunately, that's not possible currently. I struggled to find an API that provided reliable data with a free tier - and that one doesn't offer this functionality.

Additionally, I think such functionality would be hard to fit in the app design-wise, and it wouldn't offer a better experience than existing websites. The main reason behind Moneta was to offer a quick glimpse of current exchange rates during the day, which is way quicker than just searching for it online.

Thanks for the suggestion though! :smile: Unfortunately it's not one I can help with :(

**Comment by dkerkow** [comment]
What a pity. But thank you for looking into it! BR

Matheus Fantinel <notifications@github.com> schrieb am Mi., 19. Aug. 2020,
16:02:
